# Generated by Django 3.1.6 on 2021-02-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Employee:')),
                ('dep', models.CharField(max_length=30, verbose_name='Department:')),
                ('salary', models.CharField(max_length=30, verbose_name='Salary:')),
                ('position', models.CharField(max_length=30, verbose_name='Position:')),
                ('date', models.DateField(max_length=30, verbose_name='Date:')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Employee:')),
                ('date1', models.DateField(max_length=30, verbose_name='Date:')),
                ('date2', models.DateField(max_length=30, verbose_name='Date:')),
            ],
        ),
    ]
