# Generated by Django 3.1.6 on 2021-03-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(null=True, verbose_name='Salary:'),
        ),
    ]
