# Generated by Django 3.1.6 on 2021-03-15 18:27

import department.models.employee
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210312_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(validators=[department.models.employee.Employee.no_future]),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.employee'),
        ),
    ]
