# Generated by Django 3.1.6 on 2021-04-04 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20210401_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date1',
            field=models.DateField(default=datetime.date(2021, 4, 4), verbose_name='Date start:'),
        ),
    ]
