# Generated by Django 3.1.6 on 2021-03-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20210315_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='name_employee',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Employee:'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='name_vacation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.employee', to_field='name_employee'),
            preserve_default=False,
        ),
    ]
