# Generated by Django 3.1.6 on 2021-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20210315_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name_employee',
            field=models.CharField(max_length=30, unique=True, verbose_name='Employee:'),
        ),
    ]
