# Generated by Django 3.1.6 on 2021-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20210404_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date1',
            field=models.DateField(verbose_name='Date start:'),
        ),
    ]
