# Generated by Django 3.1.6 on 2021-04-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20210404_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='name_vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.employee', to_field='name_employee', unique=True),
        ),
    ]
