# Generated by Django 3.1.5 on 2021-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Employee:')),
                ('dep', models.CharField(max_length=30, verbose_name='Department:')),
                ('salary', models.CharField(max_length=30, verbose_name='Salary:')),
                ('position', models.CharField(max_length=30, verbose_name='Position:')),
                ('date', models.DateField(max_length=30, verbose_name='Date:')),
            ],
        ),
    ]
