name: Python Master Workflow
on:
  push:
    branches:
      - 'dev'
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install coveralls
          coverage run --source=mypkg -m pytest tests/
          coveralls
 

